-- Phase 40: Initial Real-Company Discovery Dataset
-- Generated by scripts/generate-phase40-seed.mjs — do not hand-edit, regenerate instead.
-- STAGING ONLY. Every company is real/public-facing, seeded unowned and unverified.
-- Idempotent: ON CONFLICT (slug) DO NOTHING, categories only assigned on first insert.

begin;

-- Toyota
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('toyota', 'Toyota', 'T', '#85C1E9', 'Japanese multinational automotive manufacturer', 'One of the world''s largest automakers, producing passenger cars, trucks, and hybrid vehicles globally.', 'toyota.com', 1937, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'toyota' and cat.slug in ('automotive') on conflict do nothing;

-- Ford Motor Company
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('ford-motor-company', 'Ford Motor Company', 'FM', '#5DADE2', 'American multinational automaker', 'A pioneer of the moving assembly line, Ford manufactures cars, trucks, and SUVs worldwide.', 'ford.com', 1903, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'ford-motor-company' and cat.slug in ('automotive') on conflict do nothing;

-- Tesla
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('tesla', 'Tesla', 'T', '#F0B27A', 'Electric vehicle and clean energy company', 'Designs and manufactures electric vehicles, battery energy storage, and solar products.', 'tesla.com', 2003, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'tesla' and cat.slug in ('automotive', 'technology') on conflict do nothing;

-- BMW
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('bmw', 'BMW', 'B', '#A9CCE3', 'German luxury vehicle and motorcycle manufacturer', 'Produces premium automobiles and motorcycles, headquartered in Munich, Germany.', 'bmw.com', 1916, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'bmw' and cat.slug in ('automotive') on conflict do nothing;

-- L'Oréal
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('l-oreal', 'L''Oréal', 'L', '#FFA07A', 'French multinational cosmetics company', 'One of the world''s largest cosmetics companies, producing skincare, haircare, makeup, and fragrance.', 'loreal.com', 1909, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'l-oreal' and cat.slug in ('shopping') on conflict do nothing;

-- Sephora
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('sephora', 'Sephora', 'S', '#85C1E9', 'Multinational beauty retailer', 'A retail chain selling cosmetics, skincare, and fragrance from hundreds of brands.', 'sephora.com', 1969, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'sephora' and cat.slug in ('shopping') on conflict do nothing;

-- The Body Shop
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('the-body-shop', 'The Body Shop', 'BS', '#5DADE2', 'British cosmetics and skincare retailer', 'Known for naturally-inspired, ethically-sourced beauty and personal care products.', 'thebodyshop.com', 1976, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'the-body-shop' and cat.slug in ('shopping') on conflict do nothing;

-- Estée Lauder
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('estee-lauder', 'Estée Lauder', 'EL', '#F0B27A', 'American skincare, makeup, and fragrance company', 'A global manufacturer and marketer of prestige skincare, makeup, and fragrance products.', 'esteelauder.com', 1946, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'estee-lauder' and cat.slug in ('shopping') on conflict do nothing;

-- Deloitte
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('deloitte', 'Deloitte', 'D', '#A9CCE3', 'Multinational professional services network', 'Provides audit, consulting, tax, and advisory services to organizations worldwide.', 'deloitte.com', 1845, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'deloitte' and cat.slug in ('business-professional-services') on conflict do nothing;

-- McKinsey & Company
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('mckinsey-and-company', 'McKinsey & Company', 'M', '#FFA07A', 'Global management consulting firm', 'Advises businesses, governments, and institutions on strategy and operations.', 'mckinsey.com', 1926, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'mckinsey-and-company' and cat.slug in ('business-professional-services') on conflict do nothing;

-- Accenture
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('accenture', 'Accenture', 'A', '#85C1E9', 'Global professional services company', 'Provides consulting, technology, and outsourcing services across industries worldwide.', 'accenture.com', 1989, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'accenture' and cat.slug in ('business-professional-services', 'technology') on conflict do nothing;

-- ADP
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('adp', 'ADP', 'A', '#5DADE2', 'Human capital management and payroll services company', 'Provides payroll processing, HR, and workforce management services to businesses.', 'adp.com', 1949, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'adp' and cat.slug in ('business-professional-services') on conflict do nothing;

-- Starbucks
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('starbucks', 'Starbucks', 'S', '#F0B27A', 'American multinational coffeehouse chain', 'Operates coffeehouses worldwide, roasting and selling coffee beans and beverages.', 'starbucks.com', 1971, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'starbucks' and cat.slug in ('food-dining') on conflict do nothing;

-- Dunkin'
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('dunkin', 'Dunkin''', 'D', '#A9CCE3', 'American coffee and baked goods chain', 'A quick-service chain known for coffee, donuts, and breakfast sandwiches.', 'dunkindonuts.com', 1950, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'dunkin' and cat.slug in ('food-dining') on conflict do nothing;

-- Peet's Coffee
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('peet-s-coffee', 'Peet''s Coffee', 'PC', '#FFA07A', 'American specialty coffee roaster and retailer', 'Founded in Berkeley, California, known for dark-roasted specialty coffee.', 'peets.com', 1966, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'peet-s-coffee' and cat.slug in ('food-dining') on conflict do nothing;

-- Costa Coffee
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('costa-coffee', 'Costa Coffee', 'CC', '#85C1E9', 'British multinational coffeehouse chain', 'A coffeehouse chain founded in London, with locations across many countries.', 'costacoffee.com', 1971, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'costa-coffee' and cat.slug in ('food-dining') on conflict do nothing;

-- Blue Bottle Coffee
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('blue-bottle-coffee', 'Blue Bottle Coffee', 'BB', '#5DADE2', 'American specialty coffee roaster', 'A specialty coffee company known for single-origin beans and cafes worldwide.', 'bluebottlecoffee.com', 2002, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'blue-bottle-coffee' and cat.slug in ('food-dining') on conflict do nothing;

-- Coursera
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('coursera', 'Coursera', 'C', '#F0B27A', 'Online learning platform', 'Partners with universities and companies to offer online courses, certificates, and degrees.', 'coursera.org', 2012, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'coursera' and cat.slug in ('education', 'technology') on conflict do nothing;

-- Khan Academy
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('khan-academy', 'Khan Academy', 'KA', '#A9CCE3', 'Nonprofit educational organization', 'Provides free online courses, lessons, and practice exercises across many subjects.', 'khanacademy.org', 2008, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'khan-academy' and cat.slug in ('education', 'business-professional-services') on conflict do nothing;

-- Duolingo
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('duolingo', 'Duolingo', 'D', '#FFA07A', 'Language-learning app and platform', 'Offers free, gamified language courses through a mobile app and website.', 'duolingo.com', 2011, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'duolingo' and cat.slug in ('education', 'technology') on conflict do nothing;

-- Udemy
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('udemy', 'Udemy', 'U', '#85C1E9', 'Online learning marketplace', 'An online marketplace where instructors create courses on a wide range of skills.', 'udemy.com', 2010, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'udemy' and cat.slug in ('education') on conflict do nothing;

-- MasterClass
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('masterclass', 'MasterClass', 'M', '#5DADE2', 'Online education subscription platform', 'Offers video lessons taught by well-known instructors across creative and professional fields.', 'masterclass.com', 2015, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'masterclass' and cat.slug in ('education') on conflict do nothing;

-- Netflix
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('netflix', 'Netflix', 'N', '#F0B27A', 'Streaming entertainment service', 'A subscription streaming service offering films, series, and documentaries worldwide.', 'netflix.com', 1997, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'netflix' and cat.slug in ('entertainment') on conflict do nothing;

-- The Walt Disney Company
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('the-walt-disney-company', 'The Walt Disney Company', 'WD', '#A9CCE3', 'American mass media and entertainment conglomerate', 'Produces films, television, and operates theme parks and streaming services.', 'disney.com', 1923, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'the-walt-disney-company' and cat.slug in ('entertainment', 'home-living') on conflict do nothing;

-- Spotify
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('spotify', 'Spotify', 'S', '#FFA07A', 'Audio streaming and media service', 'A digital music, podcast, and audio streaming platform available worldwide.', 'spotify.com', 2006, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'spotify' and cat.slug in ('entertainment') on conflict do nothing;

-- Warner Bros.
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('warner-bros', 'Warner Bros.', 'WB', '#85C1E9', 'American film and entertainment studio', 'A major film and television studio producing movies, series, and animation.', 'warnerbros.com', 1923, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'warner-bros' and cat.slug in ('entertainment') on conflict do nothing;

-- Universal Pictures
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('universal-pictures', 'Universal Pictures', 'UP', '#5DADE2', 'American film production and distribution studio', 'One of the oldest film studios in the world, producing and distributing motion pictures.', 'universalpictures.com', 1912, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'universal-pictures' and cat.slug in ('entertainment') on conflict do nothing;

-- Nike
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('nike', 'Nike', 'N', '#F0B27A', 'American athletic footwear and apparel company', 'Designs, manufactures, and markets athletic footwear, apparel, and equipment worldwide.', 'nike.com', 1964, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'nike' and cat.slug in ('shopping', 'entertainment') on conflict do nothing;

-- Zara
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('zara', 'Zara', 'Z', '#A9CCE3', 'Spanish fast-fashion clothing retailer', 'A clothing and accessories retailer, part of the Inditex group, with stores worldwide.', 'zara.com', 1975, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'zara' and cat.slug in ('shopping') on conflict do nothing;

-- H&M
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('handm', 'H&M', 'H', '#FFA07A', 'Swedish multinational clothing retailer', 'Sells clothing and accessories for men, women, teenagers, and children globally.', 'hm.com', 1947, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'handm' and cat.slug in ('shopping') on conflict do nothing;

-- Levi's
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('levi-s', 'Levi''s', 'L', '#85C1E9', 'American clothing company known for denim', 'Known for inventing blue jeans, now selling denim and casual apparel worldwide.', 'levi.com', 1853, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'levi-s' and cat.slug in ('shopping') on conflict do nothing;

-- Adidas
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('adidas', 'Adidas', 'A', '#5DADE2', 'German multinational sportswear manufacturer', 'Designs and manufactures athletic shoes, apparel, and accessories worldwide.', 'adidas.com', 1949, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'adidas' and cat.slug in ('shopping', 'entertainment') on conflict do nothing;

-- Visa
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('visa', 'Visa', 'V', '#F0B27A', 'Multinational payments technology company', 'Operates one of the world''s largest electronic payment networks.', 'visa.com', 1958, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'visa' and cat.slug in ('finance') on conflict do nothing;

-- PayPal
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('paypal', 'PayPal', 'P', '#A9CCE3', 'Online payments platform', 'Enables individuals and businesses to send and receive money online.', 'paypal.com', 1998, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'paypal' and cat.slug in ('finance', 'technology') on conflict do nothing;

-- American Express
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('american-express', 'American Express', 'AE', '#FFA07A', 'American multinational financial services company', 'Provides charge and credit card products alongside travel and financial services.', 'americanexpress.com', 1850, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'american-express' and cat.slug in ('finance') on conflict do nothing;

-- Goldman Sachs
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('goldman-sachs', 'Goldman Sachs', 'GS', '#85C1E9', 'American multinational investment bank', 'Provides investment banking, securities, and investment management services.', 'goldmansachs.com', 1869, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'goldman-sachs' and cat.slug in ('finance') on conflict do nothing;

-- Mastercard
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('mastercard', 'Mastercard', 'M', '#5DADE2', 'Multinational payments technology company', 'Operates a global payments network connecting banks, merchants, and cardholders.', 'mastercard.com', 1966, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'mastercard' and cat.slug in ('finance') on conflict do nothing;

-- McDonald's
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('mcdonald-s', 'McDonald''s', 'M', '#F0B27A', 'American fast food restaurant chain', 'One of the world''s largest fast food chains, serving burgers, fries, and more.', 'mcdonalds.com', 1940, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'mcdonald-s' and cat.slug in ('food-dining') on conflict do nothing;

-- Domino's Pizza
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('domino-s-pizza', 'Domino''s Pizza', 'DP', '#A9CCE3', 'American multinational pizza restaurant chain', 'A pizza delivery and carryout chain operating in many countries.', 'dominos.com', 1960, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'domino-s-pizza' and cat.slug in ('food-dining') on conflict do nothing;

-- Chipotle Mexican Grill
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('chipotle-mexican-grill', 'Chipotle Mexican Grill', 'CM', '#FFA07A', 'American fast casual restaurant chain', 'Serves burritos, bowls, and tacos made with a focus on responsibly-sourced ingredients.', 'chipotle.com', 1993, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'chipotle-mexican-grill' and cat.slug in ('food-dining') on conflict do nothing;

-- Subway
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('subway', 'Subway', 'S', '#85C1E9', 'American multinational sandwich chain', 'One of the world''s largest fast food chains, specializing in submarine sandwiches.', 'subway.com', 1965, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'subway' and cat.slug in ('food-dining') on conflict do nothing;

-- KFC
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('kfc', 'KFC', 'K', '#5DADE2', 'American fast food chain specializing in fried chicken', 'A fried chicken fast food chain with restaurants in over 140 countries.', 'kfc.com', 1930, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'kfc' and cat.slug in ('food-dining') on conflict do nothing;

-- CVS Health
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('cvs-health', 'CVS Health', 'CH', '#F0B27A', 'American healthcare and pharmacy company', 'Operates pharmacies, health clinics, and health insurance services across the US.', 'cvshealth.com', 1963, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'cvs-health' and cat.slug in ('health-fitness') on conflict do nothing;

-- Johnson & Johnson
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('johnson-and-johnson', 'Johnson & Johnson', 'JJ', '#A9CCE3', 'American multinational healthcare company', 'Develops pharmaceuticals, medical devices, and consumer health products.', 'jnj.com', 1886, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'johnson-and-johnson' and cat.slug in ('health-fitness') on conflict do nothing;

-- Pfizer
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('pfizer', 'Pfizer', 'P', '#FFA07A', 'American multinational pharmaceutical company', 'Researches, develops, and manufactures medicines and vaccines.', 'pfizer.com', 1849, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'pfizer' and cat.slug in ('health-fitness') on conflict do nothing;

-- Mayo Clinic
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('mayo-clinic', 'Mayo Clinic', 'MC', '#85C1E9', 'Nonprofit academic medical center', 'A nonprofit medical practice and research group focused on complex patient care.', 'mayoclinic.org', 1889, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'mayo-clinic' and cat.slug in ('health-fitness', 'business-professional-services') on conflict do nothing;

-- Peloton
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('peloton', 'Peloton', 'P', '#5DADE2', 'Interactive fitness equipment and media company', 'Sells connected exercise equipment paired with live and on-demand fitness classes.', 'onepeloton.com', 2012, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'peloton' and cat.slug in ('health-fitness', 'technology') on conflict do nothing;

-- Planet Fitness
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('planet-fitness', 'Planet Fitness', 'PF', '#F0B27A', 'American gym franchise', 'Operates a large chain of fitness centers across the United States and beyond.', 'planetfitness.com', 1992, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'planet-fitness' and cat.slug in ('health-fitness') on conflict do nothing;

-- Fitbit
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('fitbit', 'Fitbit', 'F', '#A9CCE3', 'Wearable fitness technology company', 'Makes wearable devices and software that track fitness and health metrics.', 'fitbit.com', 2007, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'fitbit' and cat.slug in ('health-fitness', 'technology') on conflict do nothing;

-- Strava
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('strava', 'Strava', 'S', '#FFA07A', 'Fitness tracking app for athletes', 'A social fitness platform for tracking running, cycling, and other activities.', 'strava.com', 2009, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'strava' and cat.slug in ('health-fitness') on conflict do nothing;

-- Gymshark
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('gymshark', 'Gymshark', 'G', '#85C1E9', 'British fitness apparel brand', 'Designs and sells gym wear and athletic apparel, sold primarily online.', 'gymshark.com', 2012, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'gymshark' and cat.slug in ('health-fitness', 'shopping') on conflict do nothing;

-- IKEA
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('ikea', 'IKEA', 'I', '#5DADE2', 'Swedish multinational furniture retailer', 'Designs and sells ready-to-assemble furniture, kitchenware, and home accessories.', 'ikea.com', 1943, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'ikea' and cat.slug in ('home-living') on conflict do nothing;

-- Williams Sonoma
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('williams-sonoma', 'Williams Sonoma', 'WS', '#F0B27A', 'American home goods retailer', 'Sells cookware, kitchenware, and home furnishings across several retail brands.', 'williams-sonoma.com', 1956, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'williams-sonoma' and cat.slug in ('home-living') on conflict do nothing;

-- Wayfair
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('wayfair', 'Wayfair', 'W', '#A9CCE3', 'American e-commerce home goods company', 'An online retailer of furniture and home goods, operating primarily through its website.', 'wayfair.com', 2002, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'wayfair' and cat.slug in ('home-living', 'shopping') on conflict do nothing;

-- Dyson
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('dyson', 'Dyson', 'D', '#FFA07A', 'British technology company', 'Designs and manufactures vacuum cleaners, fans, and other household appliances.', 'dyson.com', 1991, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'dyson' and cat.slug in ('home-living', 'technology') on conflict do nothing;

-- LEGO
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('lego', 'LEGO', 'L', '#85C1E9', 'Danish toy production company', 'Manufactures the LEGO brand of plastic construction toys and related media.', 'lego.com', 1932, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'lego' and cat.slug in ('home-living') on conflict do nothing;

-- Mattel
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('mattel', 'Mattel', 'M', '#5DADE2', 'American multinational toy manufacturer', 'Designs and manufactures toys including Barbie, Hot Wheels, and Fisher-Price.', 'mattel.com', 1945, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'mattel' and cat.slug in ('home-living') on conflict do nothing;

-- Hasbro
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('hasbro', 'Hasbro', 'H', '#F0B27A', 'American multinational toy and game company', 'Produces toys, board games, and entertainment properties for children and families.', 'hasbro.com', 1923, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'hasbro' and cat.slug in ('home-living') on conflict do nothing;

-- Toys"R"Us
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('toys-r-us', 'Toys"R"Us', 'T', '#A9CCE3', 'American toy and juvenile products retailer', 'A retail chain specializing in toys, games, and children''s products.', 'toysrus.com', 1948, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'toys-r-us' and cat.slug in ('home-living', 'shopping') on conflict do nothing;

-- The New York Times
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('the-new-york-times', 'The New York Times', 'NY', '#FFA07A', 'American daily newspaper', 'A widely-circulated newspaper and digital news publisher based in New York City.', 'nytimes.com', 1851, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'the-new-york-times' and cat.slug in ('media') on conflict do nothing;

-- BBC
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('bbc', 'BBC', 'B', '#85C1E9', 'British public service broadcaster', 'Produces news, television, and radio programming broadcast around the world.', 'bbc.com', 1922, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'bbc' and cat.slug in ('media') on conflict do nothing;

-- CNN
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('cnn', 'CNN', 'C', '#5DADE2', 'American news television channel', 'A cable news network providing 24-hour news coverage worldwide.', 'cnn.com', 1980, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'cnn' and cat.slug in ('media') on conflict do nothing;

-- The Washington Post
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('the-washington-post', 'The Washington Post', 'WP', '#F0B27A', 'American daily newspaper', 'A major newspaper based in Washington, D.C., covering national and world news.', 'washingtonpost.com', 1877, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'the-washington-post' and cat.slug in ('media') on conflict do nothing;

-- American Red Cross
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('american-red-cross', 'American Red Cross', 'AR', '#A9CCE3', 'Humanitarian nonprofit organization', 'Provides emergency assistance, disaster relief, and disaster preparedness education.', 'redcross.org', 1881, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'american-red-cross' and cat.slug in ('business-professional-services') on conflict do nothing;

-- World Wildlife Fund
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('world-wildlife-fund', 'World Wildlife Fund', 'WW', '#FFA07A', 'International conservation organization', 'Works on wildlife conservation and the reduction of humanity''s environmental footprint.', 'worldwildlife.org', 1961, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'world-wildlife-fund' and cat.slug in ('business-professional-services') on conflict do nothing;

-- Habitat for Humanity
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('habitat-for-humanity', 'Habitat for Humanity', 'HF', '#85C1E9', 'Nonprofit housing organization', 'Builds and rehabilitates affordable housing in partnership with families in need.', 'habitat.org', 1976, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'habitat-for-humanity' and cat.slug in ('business-professional-services', 'real-estate') on conflict do nothing;

-- UNICEF
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('unicef', 'UNICEF', 'U', '#5DADE2', 'United Nations agency for children''s welfare', 'Provides humanitarian and developmental aid to children worldwide.', 'unicef.org', 1946, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'unicef' and cat.slug in ('business-professional-services', 'home-living') on conflict do nothing;

-- Chewy
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('chewy', 'Chewy', 'C', '#F0B27A', 'American online pet retailer', 'An e-commerce company selling pet food, supplies, and pharmacy products.', 'chewy.com', 2011, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'chewy' and cat.slug in ('home-living', 'shopping') on conflict do nothing;

-- Petco
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('petco', 'Petco', 'P', '#A9CCE3', 'American pet supply retailer', 'Operates pet stores selling food, supplies, and health services for pets.', 'petco.com', 1965, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'petco' and cat.slug in ('home-living') on conflict do nothing;

-- PetSmart
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('petsmart', 'PetSmart', 'P', '#FFA07A', 'North American pet supply retailer', 'A large pet retail chain offering pet products, grooming, and services.', 'petsmart.com', 1986, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'petsmart' and cat.slug in ('home-living') on conflict do nothing;

-- Blue Buffalo
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('blue-buffalo', 'Blue Buffalo', 'BB', '#85C1E9', 'American pet food company', 'Manufactures natural pet food for dogs and cats.', 'bluebuffalo.com', 2002, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'blue-buffalo' and cat.slug in ('home-living') on conflict do nothing;

-- Zillow
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('zillow', 'Zillow', 'Z', '#5DADE2', 'American online real estate marketplace', 'An online platform for buying, selling, renting, and financing real estate.', 'zillow.com', 2006, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'zillow' and cat.slug in ('real-estate', 'technology') on conflict do nothing;

-- Redfin
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('redfin', 'Redfin', 'R', '#F0B27A', 'American real estate brokerage', 'A technology-powered real estate brokerage offering online home search and agent services.', 'redfin.com', 2004, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'redfin' and cat.slug in ('real-estate', 'technology') on conflict do nothing;

-- RE/MAX
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('re-max', 'RE/MAX', 'R', '#A9CCE3', 'American multinational real estate franchise', 'A franchised real estate brokerage network operating in many countries.', 'remax.com', 1973, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 're-max' and cat.slug in ('real-estate') on conflict do nothing;

-- CBRE
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('cbre', 'CBRE', 'C', '#FFA07A', 'Commercial real estate services company', 'Provides commercial real estate services and investment management worldwide.', 'cbre.com', 1906, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'cbre' and cat.slug in ('real-estate', 'business-professional-services') on conflict do nothing;

-- Amazon
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('amazon', 'Amazon', 'A', '#85C1E9', 'American multinational e-commerce and technology company', 'An e-commerce and cloud computing company offering retail, streaming, and web services.', 'amazon.com', 1994, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'amazon' and cat.slug in ('shopping', 'technology') on conflict do nothing;

-- Walmart
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('walmart', 'Walmart', 'W', '#5DADE2', 'American multinational retail corporation', 'Operates a chain of hypermarkets, discount department stores, and grocery stores.', 'walmart.com', 1962, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'walmart' and cat.slug in ('shopping') on conflict do nothing;

-- Target
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('target', 'Target', 'T', '#F0B27A', 'American retail corporation', 'Operates a chain of general merchandise and grocery discount stores.', 'target.com', 1962, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'target' and cat.slug in ('shopping') on conflict do nothing;

-- eBay
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('ebay', 'eBay', 'E', '#A9CCE3', 'American multinational e-commerce company', 'Operates an online marketplace connecting buyers and sellers worldwide.', 'ebay.com', 1995, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'ebay' and cat.slug in ('shopping', 'technology') on conflict do nothing;

-- Costco
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('costco', 'Costco', 'C', '#FFA07A', 'American multinational membership warehouse club', 'Operates membership-only warehouse clubs selling goods in bulk.', 'costco.com', 1983, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'costco' and cat.slug in ('shopping') on conflict do nothing;

-- Microsoft
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('microsoft', 'Microsoft', 'M', '#85C1E9', 'American multinational technology corporation', 'Develops, licenses, and sells computer software, consumer electronics, and cloud services.', 'microsoft.com', 1975, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'microsoft' and cat.slug in ('technology') on conflict do nothing;

-- Adobe
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('adobe', 'Adobe', 'A', '#5DADE2', 'American multinational software company', 'Creates software for creative work, document management, and digital marketing.', 'adobe.com', 1982, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'adobe' and cat.slug in ('technology') on conflict do nothing;

-- Salesforce
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('salesforce', 'Salesforce', 'S', '#F0B27A', 'American cloud-based software company', 'Provides customer relationship management (CRM) software and applications.', 'salesforce.com', 1999, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'salesforce' and cat.slug in ('technology', 'business-professional-services') on conflict do nothing;

-- Slack
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('slack', 'Slack', 'S', '#A9CCE3', 'Business communication platform', 'A messaging and collaboration platform used by teams and organizations.', 'slack.com', 2013, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'slack' and cat.slug in ('technology') on conflict do nothing;

-- Atlassian
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('atlassian', 'Atlassian', 'A', '#FFA07A', 'Australian enterprise software company', 'Develops products for software development, project management, and collaboration.', 'atlassian.com', 2002, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'atlassian' and cat.slug in ('technology') on conflict do nothing;

-- ESPN
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('espn', 'ESPN', 'E', '#85C1E9', 'American sports media company', 'Broadcasts and publishes sports programming, news, and analysis.', 'espn.com', 1979, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'espn' and cat.slug in ('entertainment', 'media') on conflict do nothing;

-- Under Armour
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('under-armour', 'Under Armour', 'UA', '#5DADE2', 'American sports apparel and equipment company', 'Designs and manufactures athletic apparel, footwear, and accessories.', 'underarmour.com', 1996, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'under-armour' and cat.slug in ('entertainment', 'shopping') on conflict do nothing;

-- Fanatics
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('fanatics', 'Fanatics', 'F', '#F0B27A', 'American licensed sports merchandise retailer', 'Sells licensed sports merchandise, apparel, and trading cards online.', 'fanatics.com', 1995, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'fanatics' and cat.slug in ('entertainment', 'shopping') on conflict do nothing;

-- Decathlon
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('decathlon', 'Decathlon', 'D', '#A9CCE3', 'French sporting goods retailer', 'Designs and sells sporting goods and equipment for a wide range of sports.', 'decathlon.com', 1976, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'decathlon' and cat.slug in ('entertainment') on conflict do nothing;

-- Apple
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('apple', 'Apple', 'A', '#FFA07A', 'American multinational technology company', 'Designs and manufactures consumer electronics, software, and online services.', 'apple.com', 1976, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'apple' and cat.slug in ('technology') on conflict do nothing;

-- Google
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('google', 'Google', 'G', '#85C1E9', 'American multinational technology company', 'Provides internet search, cloud computing, advertising, and software services.', 'google.com', 1998, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'google' and cat.slug in ('technology') on conflict do nothing;

-- Meta
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('meta', 'Meta', 'M', '#5DADE2', 'American multinational technology conglomerate', 'Builds social technology, including Facebook, Instagram, and virtual reality products.', 'meta.com', 2004, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'meta' and cat.slug in ('technology') on conflict do nothing;

-- Samsung Electronics
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('samsung-electronics', 'Samsung Electronics', 'SE', '#F0B27A', 'South Korean multinational electronics company', 'Manufactures consumer electronics, semiconductors, and mobile devices.', 'samsung.com', 1969, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'samsung-electronics' and cat.slug in ('technology') on conflict do nothing;

-- IBM
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('ibm', 'IBM', 'I', '#A9CCE3', 'American multinational technology corporation', 'Provides computer hardware, software, and consulting services worldwide.', 'ibm.com', 1911, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'ibm' and cat.slug in ('technology') on conflict do nothing;

-- Airbnb
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('airbnb', 'Airbnb', 'A', '#FFA07A', 'American online marketplace for lodging', 'An online platform connecting travelers with hosts offering short-term lodging.', 'airbnb.com', 2008, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'airbnb' and cat.slug in ('travel', 'technology') on conflict do nothing;

-- Booking.com
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('booking-com', 'Booking.com', 'B', '#85C1E9', 'Dutch online travel agency', 'An online platform for booking accommodation, flights, and travel experiences.', 'booking.com', 1996, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'booking-com' and cat.slug in ('travel', 'technology') on conflict do nothing;

-- Expedia
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('expedia', 'Expedia', 'E', '#5DADE2', 'American online travel agency', 'Provides online booking for flights, hotels, car rentals, and vacation packages.', 'expedia.com', 1996, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'expedia' and cat.slug in ('travel') on conflict do nothing;

-- TripAdvisor
insert into companies (slug, name, initials, logo_color, tagline, description, website, founded_year, organic_votes_baseline, is_seed) values ('tripadvisor', 'TripAdvisor', 'T', '#F0B27A', 'American online travel guidance platform', 'Provides traveler reviews and booking tools for hotels, restaurants, and attractions.', 'tripadvisor.com', 2000, 0, true) on conflict (slug) do nothing;
insert into company_categories (company_id, category_id) select co.id, cat.id from companies co, categories cat where co.slug = 'tripadvisor' and cat.slug in ('travel') on conflict do nothing;

commit;
